name: docs 
on:
  push:
    branches:
      - master 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-autorefs mkdocstrings mkdocstrings-python-legacy mkdocstrings-python numba pandas tabulate tqdm scipy statsmodels ir_datasets rich orjson
      - run: mkdocs gh-deploy --force
